# Generated by Django 4.2.4 on 2023-08-10 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=255, verbose_name='место')),
                ('time', models.TimeField(default='00:00:00', verbose_name='время')),
                ('action', models.CharField(max_length=255, verbose_name='действие')),
                ('is_good', models.BooleanField(default=False, verbose_name='признак приятной привычки')),
                ('frequency', models.PositiveSmallIntegerField(default=1, verbose_name='периодичность')),
                ('reward', models.CharField(blank=True, max_length=255, null=True, verbose_name='вознаграждение')),
                ('execution_time', models.TimeField(default='00:02:00', verbose_name='время на выполнение привычки')),
                ('is_public', models.BooleanField(default=False, verbose_name='признак публичности')),
                ('linked_habit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='habit_app.habit', verbose_name='cвязанная привычка')),
            ],
            options={
                'verbose_name': 'привычка',
                'verbose_name_plural': 'привычки',
            },
        ),
    ]
